### PR TITLE
Updates to website theme

### PR DESCRIPTION
**Pull request by mostro20**
Update to the latest version of the website as per what was sent over to place on staging site. Due to client requests the CSS is substantially different - barely worth comparing with the previous one. But for the other files the major change to the addition of a new region to support the cross-website navigation tabs.

### CODE REVIEW

**Comment by kehh** [comment]
@mostro20 there are conflicts that need to be resolved.

``` bash
git pull upstream master
git mergetool
# and resolve any conflicts that have arisen - probably in bstweaks.yml
git commit
git push
```

**Comment by kehh** [comment]
Also the css is css not less, which makes this theme less compatible with the other themes, and means that changes will have to be double handled. I think next time round use the `less` bootstrap starterkit, not the CDN one - that way you can edit `variables.less` and come right. But I think at this stage don't worry about it for the website.
K

**Comment by mostro20** [comment]
Will do the update tomorrow.

Re- LESS agreed - it was never the attention to go live with the CDN, I
only used that as a quick hack to get something for client to review. But
because of Magento, I never had enough time to redo it - hence where it is
now. Not making an excuse, but just giving context about why it is the way
it is. Long live Magento (which ironically, I have themed in LESS)

Cheers
Morgan

On Thursday, 30 June 2016, Kehan Harman notifications@github.com wrote:

> Also the css is css not less, which makes this theme less compatible with
> the other themes, and means that changes will have to be double handled. I
> think next time round use the less bootstrap starterkit, not the CDN one
> - that way you can edit variables.less and come right. But I think at
>   this stage don't worry about it for the website.
>   K
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/rwahs/website-theme/pull/5#issuecomment-229582879,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEU2yufZ3hVK4E25RxrWCxNO0z12dnN8ks5qQ3IcgaJpZM4JB2Yk
> .

## 

---

Morgan Strong
Gaia Resources
Environmental Technology Consultants
p +61 422 716 991
e morgan.strong@gaiaresources.com.au

## w www.gaiaresources.com.au

**Comment by mostro20** [comment]
PR can be closed as it's now resolved in PR6

**Pull request closed without merging**
